### ISSUE TITLE
QHD：后台报错日志Exception from sub cfs_instances id dhr5Br5s9tsxLGKJg Error: Match error: Expected Array

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#1619]
```
2017-12-30T08:43:15.082253165Z Exception from sub cfs_instances id XAuNx8k8kKCxa9cjB Error: Match error: Expected Array
2017-12-30T08:43:15.082298160Z     at exports.check (packages/check/match.js:34:1)
2017-12-30T08:43:15.082306113Z     at [object Object].<anonymous> (packages/steedos_workflow/server/publications/cfs_instances.coffee:3:2)
2017-12-30T08:43:15.082313736Z     at packages/matb33_collection-hooks/collection-hooks.js:281:1
2017-12-30T08:43:15.082319958Z     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2017-12-30T08:43:15.082326295Z     at [object Object]._handler (packages/matb33_collection-hooks/collection-hooks.js:280:1)
2017-12-30T08:43:15.082332550Z     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
2017-12-30T08:43:15.082338494Z     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1026:17)
2017-12-30T08:43:15.082344287Z     at [object Object].MeteorX.Subscription._runHandler (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:55:1)
2017-12-30T08:43:15.082350301Z     at [object Object].MeteorX.Session._startSubscription (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:43:1)
2017-12-30T08:43:15.082356332Z     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:617:12)
```

**Comment by sunhaolin** [comment]
由于手机客户端未更新最新代码，故传给后台数据类型是String不是Array，暂不处理
