### ISSUE TITLE
workflow err log, Error: Can't render headers after they are sent to the client

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#361]
2016-07-25 11:46:37 338: Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:776:11)
    at ServerResponse.res._renderHeaders (/srv/workflow/bundle/programs/server/npm/webapp/node_modules/connect/lib/patch.js:69:27)
    at ServerResponse.writeHead (http.js:1226:20)
    at ServerResponse.res.writeHead (/srv/workflow/bundle/programs/server/npm/webapp/node_modules/connect/lib/patch.js:75:22)
    at sendError (packages/cfs_http-methods/http.methods.server.api.js:317:1)
    at Object.thisScope.Error (packages/cfs_http-methods/http.methods.server.api.js:516:1)
    at Readable.<anonymous> (packages/cfs_access-point/access-point-handlers.js:227:1)
    at Readable.emit (events.js:95:17)
    at Request.<anonymous> (/srv/workflow/bundle/programs/server/npm/iyyang_cfs-aliyun/node_modules/aliyun-sdk/lib/request.js:372:14)
    at Request.callListeners (/srv/workflow/bundle/programs/server/npm/iyyang_cfs-aliyun/node_modules/aliyun-sdk/lib/sequential_executor.js:113:20)

**Comment by chenzhipei** [comment]
测试：通过多次连续点击下载附件，服务正常
