### ISSUE TITLE
cn err.log报错记录

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#638]
> 2016-12-15 14:22:51 919: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.res.setHeader (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
    at ServerResponse.res.setHeader (packages/steedos_cors/cors.coffee:44:20)
    at writeJsonToBody (packages/simple_json-routes/json-routes.js:132:1)
    at Object.JsonRoutes.sendResult (packages/simple_json-routes/json-routes.js:116:1)
    at packages/steedos_api/routes/collection.coffee:108:20
    at packages/simple_json-routes/json-routes.js:76:1
2016-12-16 07:17:55 952: Error: Connect timed out
    at Connection.<anonymous> (/srv/workflow/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by sunhaolin** [comment]
`JsonRoutes.sendResult res, 
            code: 200,
            data: data;`
语句之后的代码仍然会执行，所以如果执行了2次JsonRoutes.sendResult 就会报错：
`Error: Can't set headers after they are sent.`
