### ISSUE TITLE
apps 错误日志：raix_push Error: Connect timed out

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#916]
```
2017-02-10T11:48:54.165713079Z /app/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/node_modules/q/q.js:155
2017-02-10T11:48:54.165762828Z                 throw e;
2017-02-10T11:48:54.165769394Z                 ^
2017-02-10T11:48:54.165777795Z
2017-02-10T11:48:54.165783219Z Error: Connect timed out
2017-02-10T11:48:54.165789400Z     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/raix_push/node_modules/apn/lib/connection.js:193:36)
2017-02-10T11:48:54.165796979Z     at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by sunhaolin** [comment]
此问题，目前官方还未处理：
https://github.com/raix/push/issues/200
