### ISSUE TITLE
Exception from sub cms_sites id XrKcMBwT9yjCT8TM7 Error: Match error: Expected Array

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#928]
```
2017-02-15T06:59:41.685611856Z Exception from sub cms_sites id XrKcMBwT9yjCT8TM7 Error: Match error: Expected Array
2017-02-15T06:59:41.685650156Z     at exports.check (packages/check/match.js:34:1)
2017-02-15T06:59:41.685656865Z     at Subscription.<anonymous> (packages/steedos_cms/server/publications/cms_sites.coffee:6:2)
2017-02-15T06:59:41.685663028Z     at packages/matb33_collection-hooks/collection-hooks.js:281:1
2017-02-15T06:59:41.685668294Z     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2017-02-15T06:59:41.685673796Z     at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:280:1)
2017-02-15T06:59:41.685679019Z     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
2017-02-15T06:59:41.685684546Z     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
2017-02-15T06:59:41.685690500Z     at Subscription.MeteorX.Subscription._runHandler (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:55:1)
2017-02-15T06:59:41.685713803Z     at Session.MeteorX.Session._startSubscription (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:43:1)
2017-02-15T06:59:41.685720048Z     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
2017-02-15T06:59:41.685760485Z Sanitized and reported to the client as: Match failed [400]
```

**Comment by sunhaolin** [comment]
此报错为 cms_sites.coffee中
```
check spaces, Array
```
校验引起，为正常报错
