### ISSUE TITLE
Exception from sub instance_tabular id rZiH3NWEWbDAFSpck TypeError: Cannot set property 'is_read' of undefined

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#929]
```
2017-02-15T06:58:39.714421526Z Exception from sub instance_tabular id rZiH3NWEWbDAFSpck TypeError: Cannot set property 'is_read' of undefined
2017-02-15T06:58:39.714470330Z     at packages/steedos_workflow/server/publications/instance_tabular.coffee:78:4
2017-02-15T06:58:39.714477623Z     at Array.forEach (native)
2017-02-15T06:58:39.714483260Z     at Subscription.<anonymous> (packages/steedos_workflow/server/publications/instance_tabular.coffee:72:6)
2017-02-15T06:58:39.714490709Z     at packages/matb33_collection-hooks/collection-hooks.js:281:1
2017-02-15T06:58:39.714550744Z     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
2017-02-15T06:58:39.714556863Z     at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:280:1)
2017-02-15T06:58:39.714562518Z     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
2017-02-15T06:58:39.714569295Z     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
2017-02-15T06:58:39.714576027Z     at Subscription.MeteorX.Subscription._runHandler (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:55:1)
2017-02-15T06:58:39.714602005Z     at Session.MeteorX.Session._startSubscription (packages/meteorhacks_unblock/packages/meteorhacks_unblock.js:43:1)
```

**Comment by sunhaolin** [comment]
此问题是在修改申请单 未读状态 到已读状态时发生，请测试人员了解。
