### ISSUE TITLE
apps error导致服务停止Error: read ECONNRESET

### ISSUE THREAD

**Issue by sunhaolin** [steedos/apps#930]
```
2017-02-15T06:56:24.145252208Z events.js:141
2017-02-15T06:56:24.145334712Z       throw er; // Unhandled 'error' event
2017-02-15T06:56:24.145344025Z       ^
2017-02-15T06:56:24.145350088Z
2017-02-15T06:56:24.145356338Z Error: read ECONNRESET
2017-02-15T06:56:24.145362052Z     at exports._errnoException (util.js:907:11)
2017-02-15T06:56:24.145367628Z     at TCP.onread (net.js:558:26)
```

**Comment by sunhaolin** [comment]
猜测由于网络原因导致发送推送消息或者邮件失败导致此错误
